const SEQ_BLOCK_WIDTH = 24;
const SEQ_BLOCK_HEIGHT = 24;
const SEQ_GAP_BACKGROUND = [255, 255 ,255];
const AUTO_SCROLL_X = 1;
const AUTO_SCROLL_Y = 1;

export { SEQ_BLOCK_WIDTH, SEQ_BLOCK_HEIGHT, SEQ_GAP_BACKGROUND, AUTO_SCROLL_X, AUTO_SCROLL_Y };
